<?php

return [
    [
        'title' => 'Project 1',
        'description' => 'Lorem ipsum dolor sit amet.',
        'start_date' => '2023-01-15',
        'end_date' => '2023-02-28',
        'completed' => true,
        'created_by' => 1,
        'budget' => 5000.00,
    ],
    [
        'title' => 'Project 2',
        'description' => 'Consectetur adipiscing elit.',
        'start_date' => '2023-03-10',
        'end_date' => '2023-05-20',
        'completed' => false,
        'created_by' => 2,
        'budget' => 8000.00,
    ],
    [
        'title' => 'Project 3',
        'description' => 'Sed do eiusmod tempor incididunt ut labore.',
        'start_date' => '2023-06-01',
        'end_date' => '2023-07-15',
        'completed' => false,
        'created_by' => 3,
        'budget' => 3000.00,
    ],
    [
        'title' => 'Project 4',
        'description' => 'Ut enim ad minim veniam.',
        'start_date' => '2023-08-10',
        'end_date' => '2023-09-30',
        'completed' => true,
        'created_by' => 1,
        'budget' => 7000.00,
    ],
    [
        'title' => 'Project 5',
        'description' => 'Duis aute irure dolor in reprehenderit.',
        'start_date' => '2023-10-01',
        'end_date' => '2023-11-15',
        'completed' => false,
        'created_by' => 2,
        'budget' => 6000.00,
    ],
    [
        'title' => 'Project 6',
        'description' => 'Excepteur sint occaecat cupidatat non proident.',
        'start_date' => '2023-12-01',
        'end_date' => '2024-01-31',
        'completed' => false,
        'created_by' => 3,
        'budget' => 4000.00,
    ],
    [
        'title' => 'Project 7',
        'description' => 'Sunt in culpa qui officia deserunt mollit anim.',
        'start_date' => '2024-02-15',
        'end_date' => '2024-04-10',
        'completed' => true,
        'created_by' => 1,
        'budget' => 9000.00,
    ],
    [
        'title' => 'Project 8',
        'description' => 'Lorem ipsum dolor sit amet.',
        'start_date' => '2024-05-01',
        'end_date' => '2024-06-30',
        'completed' => false,
        'created_by' => 2,
        'budget' => 5500.00,
    ]
    ];